"""added a weight column in 'edge' model with a default value set to 1.0

Revision ID: 7a3ce3be002d
Revises: e6c3b48a8ad4
Create Date: 2026-04-02 00:14:42.392084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a3ce3be002d'
down_revision: Union[str, Sequence[str], None] = 'e6c3b48a8ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demands', 'scenario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('demands', 'source',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('demands', 'target',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('demands', 'traffic',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('edges', sa.Column('weight', sa.Float(), nullable=False))
    op.alter_column('edges', 'scenario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('edges', 'source',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('edges', 'target',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('edges', 'capacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('nodes', 'scenario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('nodes', 'external_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('scenarios', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('scenarios', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('scenarios', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('scenarios', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('scenarios', 'created_at')
    op.alter_column('nodes', 'external_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('nodes', 'scenario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('edges', 'capacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('edges', 'target',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('edges', 'source',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('edges', 'scenario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('edges', 'weight')
    op.alter_column('demands', 'traffic',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('demands', 'target',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('demands', 'source',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('demands', 'scenario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
