"""optimization_table

Revision ID: cd649bf376fe
Revises: 7a3ce3be002d
Create Date: 2026-05-03 15:55:26.269525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd649bf376fe'
down_revision: Union[str, Sequence[str], None] = '7a3ce3be002d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('routing_type', sa.String(), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=False),
    sa.Column('paths', sa.String(), nullable=False),
    sa.Column('duals', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimization_results')
    # ### end Alembic commands ###
